# Generated by Django 2.0.2 on 2018-05-14 10:40

from django.db import migrations, models
import jobboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(default=jobboard.models.get_deadline)),
                ('wordcount', models.IntegerField()),
                ('jobtaken', models.BooleanField(default=False)),
            ],
        ),
    ]
